version: '3.8'

services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.11.0
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_ARTIFACT_ROOT=/mlflow/artifacts
      - MLFLOW_SERVER_HOST=0.0.0.0
    volumes:
      - mlflow_data:/mlflow
      - ./artifacts:/app/artifacts
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts --host 0.0.0.0 --port 5000
  task3:
    build: .
    depends_on:
      - mlflow
    volumes:
      - ./src:/app/src
      - ./artifacts:/app/artifacts
      - ./local_data:/app/local_data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: >
      sh -c "echo 'Ожидание запуска MLflow...' &&
             sleep 15 &&
             echo 'Запуск задания 3...' &&
             python /app/src/data/prepare_data.py &&
             python /app/src/models/trainer.py &&
             python /app/src/mlflow_utils/registry.py &&
             echo '✅ ЗАДАНИЕ 3 ВЫПОЛНЕНО!'"

volumes:
  mlflow_data: